import { Avatar, Card, Grid } from '@mui/material';
import Head from 'next/head';
import Image from 'next/image';
import PricingForm from '../components/PricingForm';
import styles from '../styles/Home.module.css';
import logo from '../public/logo/Untitled.png';
export default function Home() {
  return (
    <Card
      className={styles.body}
      sx={{
        marginTop: 10,
        borderRadius: 5,
        background: '#ffffff',
        textAlign: 'center',
        overflow: 'initial',
      }}
    >
      <Head>
        <title>EP Pricing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.title}>
        <Grid container alignItems="center" justifyContent="center">
          <Grid>
            <Image src={logo} alt="Logo" width={64} height={64} />
          </Grid>
          <Grid>
            <h1>EP Pricing</h1>
          </Grid>
        </Grid>
      </header>

      <main className={styles.main}>
        <PricingForm />
      </main>

      <footer className={styles.footer}>ⒸInternal Use</footer>
    </Card>
  );
}
